name: pytorch-playground
channels:
- defaults
- conda-forge
- ericmjl
- pytorch
- rdkit
dependencies:
- python=3.6
- pandas
- scipy
- pyjanitor
- scikit-learn
- matplotlib
- seaborn
- missingno
- pytorch
- rdkit
